import { Bien, BienKpis, MovimientoBien } from './inventario.model';

export const BIENES_MOCK: Bien[] = [
  {
    id: 1,
    codigoSena: 'EQU-2024-001',
    codigoProveedor: 'PRV-992-B',
    descripcion: 'Core i7, 16GB RAM, 512GB SSD',
    categoria: 'Equipos de Cómputo',
    categoriaColor: 'blue',
    stockActual: 15,
    stockMinimo: 5,
    unidadMedida: 'UND',
    valorNeto: 3781512,
    iva: 19,
    valor: 4500000,
    estado: 'Activo',
    estadoStock: 'DISPONIBLE',
    tieneHistorial: true,
    proveedor: 'Dell Colombia S.A.S.',
    fechaCompra: '2024-01-10',
    factorConversion: 1,
    depreciacionAnual: 20,
    especificaciones: {
      'Procesador': 'Intel Core i7 11th Gen',
      'Memoria RAM': '16GB DDR4',
      'Almacenamiento': '512GB SSD NVMe',
      'Sistema Operativo': 'Windows 11 Pro',
      'Código Activo': 'EQU-2024-001',
      'Fecha Compra': '12 Ene 2024',
    },
    facturas: [
      { id: 1, fel: 'FEL-99281', cufe: 'e3b0c442...855', proveedor: 'Dell Colombia S.A.S.', fecha: '2024-01-10', monto: 4500000, estado: 'PAGADA' },
      { id: 2, fel: 'FEL-98745', cufe: '8d969eef...c92', proveedor: 'Distribuidora Tecnológica', fecha: '2023-11-05', monto: 120000, estado: 'CAUSADA' },
    ],
  },
  {
    id: 2,
    codigoSena: 'PAP-2024-042',
    codigoProveedor: 'PRV-118-P',
    descripcion: 'Caja x 10 resmas',
    categoria: 'Papelería',
    categoriaColor: 'amber',
    stockActual: 4,
    stockMinimo: 10,
    unidadMedida: 'UND',
    valorNeto: 100840,
    iva: 19,
    valor: 120000,
    estado: 'Bajo Stock',
    estadoStock: 'BAJO_STOCK',
    tieneHistorial: false,
    proveedor: 'Papelería Nacional S.A.',
    fechaCompra: '2024-03-15',
    factorConversion: 1,
    facturas: [],
  },
  {
    id: 3,
    codigoSena: 'MOB-2024-015',
    codigoProveedor: 'PRV-445-M',
    descripcion: 'Respaldo en malla, ajuste lumbar',
    categoria: 'Mobiliario',
    categoriaColor: 'green',
    stockActual: 32,
    stockMinimo: 10,
    unidadMedida: 'UND',
    valorNeto: 714286,
    iva: 19,
    valor: 850000,
    estado: 'Activo',
    estadoStock: 'DISPONIBLE',
    tieneHistorial: true,
    proveedor: 'Muebles y Más S.A.S.',
    fechaCompra: '2024-02-20',
    factorConversion: 1,
    facturas: [],
  },
  {
    id: 4,
    codigoSena: 'COC-2024-088',
    codigoProveedor: 'PRV-221-C',
    descripcion: 'Acero inoxidable 304, fondo difusor',
    categoria: 'Cocina',
    categoriaColor: 'purple',
    stockActual: 6,
    stockMinimo: 8,
    unidadMedida: 'UND',
    valorNeto: 1008403,
    iva: 19,
    valor: 1200000,
    estado: 'Bajo Stock',
    estadoStock: 'BAJO_STOCK',
    tieneHistorial: true,
    proveedor: 'Equipo Chef Colombia',
    fechaCompra: '2024-01-25',
    factorConversion: 1,
    facturas: [],
  },
];

export const BIENES_KPIS_MOCK: BienKpis = {
  valorTotal: 458240000,
  totalAlertas: 23,
  movimientosHoy: 156,
  tendenciaValor: 12,
};

export const MOVIMIENTOS_MOCK: MovimientoBien[] = [
  { id: 1, fecha: '2024-05-14', tipo: 'ENTRADA', responsable: 'Admin Central', ubicacion: 'Almacén General', cantidad: 5, observacion: 'Reposición de stock anual' },
  { id: 2, fecha: '2024-04-22', tipo: 'SALIDA', responsable: 'Coord. Sistemas', ubicacion: 'Laboratorio 302', cantidad: -2, observacion: 'Asignación a nuevos instructores' },
  { id: 3, fecha: '2024-03-10', tipo: 'TRASLADO', responsable: 'Gestión Activos', ubicacion: 'Sede Norte', cantidad: 0, observacion: 'Mantenimiento preventivo trimestral' },
];
