import { SolicitudGil } from './solicitudes-gil.model';

export const SOLICITUDES_GIL_MOCK: SolicitudGil[] = [
  {
    id: 1,
    codigo: 'GIL-F-014-2024-001',
    fecha: '24 Oct, 2024',
    centroCostos: 'CBA Mosquera',
    area: 'Gastronomía',
    cuentadante: 'Carlos Alberto Ruiz',
    destino: 'Cocina Principal',
    ficha: 'ADSO-2670687',
    estado: 'Borrador',
    totalBienes: 8,
    montoTotal: 1240000,
    avatarColor: 'blue',
  },
  {
    id: 2,
    codigo: 'GIL-F-014-2024-002',
    fecha: '22 Oct, 2024',
    centroCostos: 'CBA Mosquera',
    area: 'Mantenimiento',
    cuentadante: 'Martha Lucía Gomez',
    destino: 'Taller Técnico',
    ficha: 'MANT-2550122',
    estado: 'Pendiente',
    totalBienes: 5,
    montoTotal: 450500,
    avatarColor: 'purple',
  },
  {
    id: 3,
    codigo: 'GIL-F-014-2024-003',
    fecha: '20 Oct, 2024',
    centroCostos: 'CBA Mosquera',
    area: 'Gestión Empresarial',
    cuentadante: 'Fernando Vallejo',
    destino: 'Aula 301',
    ficha: 'GEST-2899341',
    estado: 'Validado',
    totalBienes: 12,
    montoTotal: 2890000,
    avatarColor: 'amber',
  },
  {
    id: 4,
    codigo: 'GIL-F-014-2024-004',
    fecha: '18 Oct, 2024',
    centroCostos: 'CBA Mosquera',
    area: 'Gastronomía',
    cuentadante: 'Lucía Mercedes Prada',
    destino: 'Cocina Caliente',
    ficha: 'ADSO-2670687',
    estado: 'Aprobado',
    totalBienes: 20,
    montoTotal: 3150000,
    avatarColor: 'green',
  },
  {
    id: 5,
    codigo: 'GIL-F-014-2024-005',
    fecha: '15 Oct, 2024',
    centroCostos: 'CBA Mosquera',
    area: 'Mantenimiento',
    cuentadante: 'Roberto Jaramillo',
    destino: 'Laboratorio',
    ficha: 'MANT-2550122',
    estado: 'Procesado',
    totalBienes: 6,
    montoTotal: 890000,
    avatarColor: 'slate',
  },
];
