import { EnvironmentProviders, makeEnvironmentProviders } from '@angular/core';
import {
  LucideAlertCircle,
  LucideAlertTriangle,
  LucideArrowLeft,
  LucideArrowLeftRight,
  LucideBadge,
  LucideBanknote,
  LucideBarChart,
  LucideBarChart2,
  LucideBell,
  LucideBox,
  LucideBuilding2,
  LucideCalendar,
  LucideCheckCircle,
  LucideCheckSquare,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronsUpDown,
  LucideCircleDollarSign,
  LucideClipboardCheck,
  LucideClock,
  LucideCloudDownload,
  LucideCreditCard,
  LucideDownload,
  LucideExternalLink,
  LucideEye,
  LucideFileCode,
  LucideFileDown,
  LucideFileSpreadsheet,
  LucideFileStack,
  LucideFileText,
  LucideFilter,
  LucideGraduationCap,
  LucideHistory,
  LucideIcon,
  LucideIconData,
  LucideInfo,
  LucideLandmark,
  LucideLayoutDashboard,
  LucideLibrary,
  LucideLightbulb,
  LucideList,
  LucideListFilter,
  LucideLogOut,
  LucideMinus,
  LucideMoreVertical,
  LucidePackage,
  LucidePackageCheck,
  LucidePencil,
  LucidePieChart,
  LucidePlus,
  LucidePlusCircle,
  LucidePrinter,
  LucideReceipt,
  LucideRefreshCw,
  LucideSave,
  LucideScale,
  LucideSearch,
  LucideSettings,
  LucideShare,
  LucideShieldCheck,
  LucideSlidersHorizontal,
  LucideTable,
  LucideTrash2,
  LucideTrendingUp,
  LucideTriangleAlert,
  LucideUpload,
  LucideUploadCloud,
  LucideUser,
  LucideUserCircle,
  LucideWallet,
  LucideWarehouse,
  LucideX,
  LucideXCircle,
  provideLucideIcons,
} from '@lucide/angular';

export type RestaurantUiIcon = LucideIcon | LucideIconData;

export interface ProvideRestaurantUiOptions {
  icons?: RestaurantUiIcon[];
}

export const RESTAURANT_UI_BASE_ICONS: RestaurantUiIcon[] = [
  LucideAlertCircle,
  LucideAlertTriangle,
  LucideArrowLeft,
  LucideArrowLeftRight,
  LucideBadge,
  LucideBanknote,
  LucideBarChart,
  LucideBarChart2,
  LucideBell,
  LucideBox,
  LucideBuilding2,
  LucideCalendar,
  LucideCheckCircle,
  LucideCheckSquare,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronsUpDown,
  LucideCircleDollarSign,
  LucideClipboardCheck,
  LucideClock,
  LucideCloudDownload,
  LucideCreditCard,
  LucideDownload,
  LucideExternalLink,
  LucideEye,
  LucideFileCode,
  LucideFileDown,
  LucideFileSpreadsheet,
  LucideFileStack,
  LucideFileText,
  LucideFilter,
  LucideGraduationCap,
  LucideHistory,
  LucideInfo,
  LucideLandmark,
  LucideLayoutDashboard,
  LucideLibrary,
  LucideLightbulb,
  LucideList,
  LucideListFilter,
  LucideLogOut,
  LucideMinus,
  LucideMoreVertical,
  LucidePackage,
  LucidePackageCheck,
  LucidePencil,
  LucidePieChart,
  LucidePlus,
  LucidePlusCircle,
  LucidePrinter,
  LucideReceipt,
  LucideRefreshCw,
  LucideSave,
  LucideScale,
  LucideSearch,
  LucideSettings,
  LucideShare,
  LucideShieldCheck,
  LucideSlidersHorizontal,
  LucideTable,
  LucideTrash2,
  LucideTrendingUp,
  LucideTriangleAlert,
  LucideUpload,
  LucideUploadCloud,
  LucideUser,
  LucideUserCircle,
  LucideWallet,
  LucideWarehouse,
  LucideX,
  LucideXCircle,
];

export function provideRestaurantUi(
  options: ProvideRestaurantUiOptions = {},
): EnvironmentProviders {
  return makeEnvironmentProviders([
    provideLucideIcons(...RESTAURANT_UI_BASE_ICONS, ...(options.icons ?? [])),
  ]);
}
